---
kind: pipeline
name: default
steps:
- name: test
  image: golang:1.10-alpine
  commands:
   - "go test"
- name: build
  image: golang:1.10-alpine
  commands:
   - "go build -o ./myapp" 
- name: publish  
  image: plugins/gcr
  settings:
    repo: eu.gcr.io/king-up-prod/go-sample-app
    tags: latest
    json_key: 
      from_secret: google_credentials
- name: deliver
 image: king-up-prod/drone-kubectl
 settings:
   kubernetes_server:
     from_secret: k8s_server
   kubernetes_cert:
     from_secret: k8s_cert
   kubernetes_token:
     from_secret: k8s_token
 commands:
   - kubectl apply -f deployment.yml