---
kind: pipeline
name: default
steps:
- name: test
  image: golang:1.10-alpine
  commands:
   - "go test"
- name: build
  image: golang:1.10-alpine
  commands:
   - "go build -o ./myapp"
- name: publish
  image: plugins/docker
  settings:
   repo: eu.gcr.io/king-up-prod/portal-sample-app 
   tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
   username:
     from_secret: docker_username
   password:
     from_secret: docker_password
