language: go

env:
  - DOCKER_USER=mboronin REPO=mboronin/travis TAG=latest

services:
  - docker

script:
    - go test -v
    - go build -o ./myapp

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO